### ISSUE TITLE
Not sure how to use filter option

### ISSUE THREAD

**Issue by bsima** [adzerk-oss/boot-test#15]
Instructions aren't very clear (at least to me they aren't). Could someone provide a working example? I think it would be really helpful for an example that will only run namespaces with "test" in the name:

```
$ boot test -f "(re-matcher #\".*test.*\" %)"
```

I couldn't get the above to work. I tried a bunch of different things to no avail:

```
$ boot test -f "(re-matcher #\".*utility-belt\$\" (str %))"
```

The above ran all my tests; I was just trying to run the `test.utility-belt` namespace

```
$ boot test -f "(= \"test.utility-belt\" %)"
```

This started the test runner, printed out the names of all of my namespaces, and ran zero tests.

**Comment by magomimmo** [comment]
@bsima did you find your way to call `-f` option? I ran in the same difficulty. Moreover I do not understand why `test` task runs all namespaces when `-n` is not set. I never saw a regular namespace containing tests, even if clojure allows it to test private symbols inside the namespace defining them.  IMHO that choice made `test` task non compatible with a TDD workflow. Could be better to have a `[t dirs PATH #{str} "the test dirs"]` options for setting the directories containing tests?

**Comment by tdavis** [comment]
This is a long time gone, but in case you or anyone needs to use the filter option in the future:

```clojure
(bt/test :filters #{'(re-find #"^overmind\.test\..+-test$" (-> % meta :ns str))})
```

Basically, you were close @bsima, but you need to keep in mind that the value of ``%`` is actually a Var in the namespace, not the namespace itself. You need to interrogate the metadata if you want to do any namespace comparison. The example above runs anything named ``*-test`` in the ``overmind.test`` namespace. If you want to debug the filter, you can add a print:

```clojure
(bt/test :filters #{'(let [res (re-find #"^overmind\.test\..+-test$" (-> % meta :ns str))] (println res) res)})
```

Hope this helps!

**Comment by aft-luke** [comment]
Is there similar support for `:namespaces`? I don't want to manually type in `my.namespace-test another.namespace-test a-third.namespace-test` when I want to run these, or have to add each and every namespace to a boot file. A lot of runners in other languages expose some sort of `run-all --matching .*-test` regex support.

**Comment by tdavis** [comment]
Not sure I understand the question, @aft-luke. The example I provided is a regex on the entire 
namespace, you can substitute it for your own. For your example, ``#"-test$"`` should suffice.

**Comment by aft-luke** [comment]
I think my problem was conceptual with how namespaces work in general. Coming from the javascript world, I would normally setup a test suite to allow me to invoke something like `test ./some-feat/**/*-test.js`, where I could glob match on a particular feature or set of features. The purpose being the tests run much faster against only a handful of tests versus the whole suite. With clojure (cljs) namespaces, perhaps the files and dirs don't really matter, I could still just match on namespaces via `{feature-name}.**.*-test$` or something similar?

**Comment by tdavis** [comment]
> I could still just match on namespaces via {feature-name}.**.*-test$ or something similar?
Essentially, yes. 

What boot-test provides is actually much better because the idea of what is being run is divorced from the filesystem layout entirely. What the filter function receives is a ``Var``, which is a pointer to a named symbol somewhere. The Var also has metadata attached to it. Metadata is arbitrary, but part of what you get in a Var is its namespace--the ``ns`` key (http://clojure.org/reference/namespaces). 

If you want to run a particular namespace from the command line more easily, you could create a new Boot task that takes an argument (``{feature-name}`` in your example) then construct the regex to pass to ``test`` in your task.

**Comment by daveyarwood** [comment]
I think the `filter` task is a nice thing to have because of its flexibility and usefulness in complicated testing setups, but #21 should make it a lot easier to specify which tests should be run via a regex.

**Comment by daveyarwood** [comment]
Including/excluding namespaces by regex is now supported (#30). I think the `filter` option is explained well in this issue, so this issue is OK to close.
