### ISSUE TITLE
junit output-to support one single file

### ISSUE THREAD

**Issue by nha** [adzerk-oss/boot-test#29]
Some CI environnements (I believe circleCI is one of them) expect only one single junit xml result file.

I currently use an external script like https://www.npmjs.com/package/junit-report-merger but it would be nice if this was an argument to boot-test (or a separate task).

**Comment by nberger** [comment]
Hi @nha!

This doesn't seem to be an issue in CircleCI. It can perfectly pick up junit reports from multiple files, I've been using it in my work projects for a while, all having multiple test namespaces.

As an example, I added a couple test namespaces with test failures in my fork of boot-test, and CircleCI shows all of them. You can see an example build result in https://circleci.com/gh/nberger/boot-test/5. Check out both the Test Summary and the Artifacts tab, you'll find 3 xml files, one for each test ns.

Perhaps this is an issue in other build environments, but not in CircleCI.

**Comment by nha** [comment]
I can confirm it works. Thanks!
